micronaut:
  application:
    name: email-app
  server:
    port: 8084
netty:
  default:
    allocator:
      max-order: 3
#tag::mail[]
---
micronaut:
  email:
    from:
      name: 'Email-App' //senders' name
      email: 'syedubed09@gmail.com' //senders' email
#end::mail[]
